"""empty message

Revision ID: 2dcb82b495e2
Revises: a4c8bb047e84
Create Date: 2020-07-23 04:43:35.967814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcb82b495e2'
down_revision = 'a4c8bb047e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('artists', 'seeking_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
